// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback:                       1
// Total number of exported functions:   7

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    elven_nft_minter
    (
        init => init
        upgrade => upgrade
        getNftTokenId => nft_token_id
        mint => mint
        issueToken => issue_token
        setLocalRoles => set_local_roles
    )
}

multiversx_sc_wasm_adapter::async_callback! { elven_nft_minter }
